### ISSUE TITLE
Reduce Verbosity?

### ISSUE THREAD

**Issue by MrColdbird** [MrColdbird/lobbyemu#21]
While I have analyzed the TX buffer issue (and consequently fixed it), I have come to understand that the huge amount of verbose output we have (in three different logfiles) is causing a lot of slowdowns in RX processing (which doesn't come as a surprise), eventually resulting in connection timeouts. Not because the connection is bad, but rather because the server is busy logging data it shouldn't even log (anymore).

This issue has been opened to discuss how we are going to proceed with the server connection handling.

I think that 99% of our timeout issues can be solved by increasing the connection timeout from 30 to 60 seconds, and by removing / disabling all the needlessly verbose output we produce, but you guys might have a different opinion about it.

Other options would include refactoring the server connection code to be multithreaded, rather than using a rotational queue, but this in turn would make live-debugging a lot more difficult because of the huge amount of threads spawned.

Also, threads have a rather huge overhead in memory due to their preallocated stack size, etc.

I will leave this ticket open until this weekend, at which point I will just disable the verbose output should no other decision be made.

Greetings, Coldbird

**Comment by kamijoutouma** [comment]
I think that we should reduce the amount of verbose by providing a global bool called noisy and logging certain things only if noisy is true. Instead of just disabling it.
Also i have a lot of 0kb log files so we might want to make certain catches to not create a log file if there isn't any data to be logged.

**Comment by NCDyson** [comment]
I believe most, if not all the logging can be disabled if not removed at this point. Back in the early stages of the project it was helpful, but now it seems mostly to be an annoyance. 

Increasing the timeout to 60 also seems like a reasonable idea as well.

As far as switching to a multi-threaded server architecture, I personally have very little experience with multi-threading, and I'm not going to lie, it sounds like a massive pain. 

I'm also not particularly sure how well the current method will work if there is ever a time when we will see a lot more connections. I don't personally see fragment being a game where the number of players online at any given time will measure in the 100s, but things like the air_gamer's Lobby Status Notifier and many users hosting multiple area servers do tend to increase the number of active connections to the server. 

At some point in the future we may have to switch to a multi-threaded system, but presently, if we can get by with the current method, I'd much rather work with that and get the rest of the system operational.

**Comment by kamijoutouma** [comment]
Closing this now as its been 2 weeks and the changes have been made.
